### ISSUE TITLE
Simpler USB Installation Media

### ISSUE THREAD

**Issue by ryneeverett** [chris-martin/chris-martin.org#3]
In http://chris-martin.org/2015/installing-nixos you write:

> Load it onto a flash drive using unetbootin.

> (I don’t know if there’s a better way to do this. Creating USB install media is still a huge mystery to me; I don’t get why it’s so complicated or why there’s seemingly no authoritative method.)

`dd` is much simpler and IMO the authoritative method:

```sh
dd bs=4M if=/path/to/nixos-*.iso of=/dev/sdx && sync
```

See [this wiki page](https://wiki.archlinux.org/index.php/USB_flash_installation_media#Using_dd).

**Comment by chris-martin** [comment]
I know I've tried and failed to create boot media with `dd` in the past, though I don't recall why.

Any idea why unetbootin is the only method recommended by the [NixOS manual](https://nixos.org/nixos/manual/index.html)?

**Comment by ryneeverett** [comment]
> I know I've tried and failed to create boot media with dd in the past, though I don't recall why.

The thing people usually get wrong is setting `of=` to a partition rather than the whole device.

I couldn't tell you why unetbootin is recommended. I've tried it a few times and rarely get it to work.

**Comment by chris-martin** [comment]
I haven't revisited this, and I don't want to recommend anything I haven't tried.
