### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [chris-martin/chris-martin.org#8]
I would like to be notified when you post new stuff. I don't always catch it on Twitter. Could you add an Atom or RSS feed?

**Comment by chris-martin** [comment]
Will do.

**Comment by chris-martin** [comment]
@tfausak Feed is up. I don't use RSS, personally, so I'd love to hear whether it's working for you.

**Comment by tfausak** [comment]
There are some validation errors, but it's useful to me in spite of those: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fchris-martin.org%2Frss.xml

Thanks for taking the time to do this!

**Comment by chris-martin** [comment]
opened #15
